import type { FraudCase, GraphEdge, GraphNode, PastCase, Transaction } from "./types";

/**
 * Mock data shaped like HHGOA_IEEE (IEEE-CIS: TransactionID, TransactionAmt, ProductCD,
 * card1-6, P_emaildomain, DeviceInfo, id_* ...). Swap for the TigerGraph adapter in lib/tigergraph.ts
 * once the dataset is loaded.
 */

export const FRAUD_PATTERNS = [
  {
    id: "P1",
    name: "Card testing",
    description: "Burst of low-value authorisations followed by a high-value purchase on the same card.",
    keySignals: ["smallAuthsBeforeLarge", "velocity1h"],
  },
  {
    id: "P2",
    name: "Account takeover",
    description: "New or unrecognised device, recent profile changes, and spend far outside the customer's baseline.",
    keySignals: ["newDevice", "addrChanged7d", "amountZ"],
  },
  {
    id: "P3",
    name: "Mule / shared-device ring",
    description: "Many cards transacting through one device or IP, graph-connected to previously confirmed fraud.",
    keySignals: ["cardsOnDevice", "cardsOnIp", "hopsToConfirmedFraud"],
  },
  {
    id: "P4",
    name: "Synthetic identity",
    description: "Young identity with mismatched email domains, fresh address and thin history.",
    keySignals: ["emailDomainMismatch", "addrChanged7d", "deviceAgeDays"],
  },
  {
    id: "P5",
    name: "First-party (friendly) fraud",
    description: "Customer disputes a transaction made from their own long-standing device and address.",
    keySignals: ["customerReported", "deviceAgeDays"],
  },
] as const;

export const POLICY = {
  sarThresholdUsd: 5000,
  autoBlockMinRisk: 0.9,
  autoBlockMinConfidence: 0.8,
  actToConfidence: 0.82,
  maxEvidenceRounds: 2,
  sections: {
    block: "Fraud Policy §3.1 — Transaction blocking",
    freeze: "Fraud Policy §3.4 — Account restriction requires analyst approval",
    sar: "Fraud Policy §6.2 / 31 CFR 1020.320 — SAR when suspected fraud ≥ $5,000 or organised activity",
    stepUp: "Fraud Policy §2.3 — Step-up authentication on unrecognised device",
    contact: "Fraud Policy §2.5 — Customer contact via verified channel only",
    friendly: "Fraud Policy §5.1 — Disputes on known devices require merchant evidence",
    monitor: "Fraud Policy §4.0 — Enhanced monitoring 30 days",
  },
};

const t = (
  id: string,
  ts: string,
  amount: number,
  merchant: string,
  riskScore: number,
  extra: Partial<Transaction> = {},
): Transaction => ({ id, ts, amount, merchant, riskScore, productCD: "W", ...extra });

function g(nodes: [string, GraphNode["kind"], string, Partial<GraphNode>?][], edges: [string, string, string][]) {
  return {
    nodes: nodes.map(([id, kind, label, extra]) => ({ id, kind, label, ...extra })) as GraphNode[],
    edges: edges.map(([from, to, label]) => ({ from, to, label })) as GraphEdge[],
  };
}

export const CASES: FraudCase[] = [
  {
    id: "HHG-2041",
    title: "Burst of micro-authorisations before $2,480 electronics purchase",
    trigger: "risk_score",
    triggerDetail: "Model risk score 0.94 on TransactionID 3577412",
    openedAt: "2026-09-24T08:12:00Z",
    customer: { id: "C-10492", name: "Customer 10492", tenureMonths: 31, segment: "Retail" },
    subjectTxnId: "3577412",
    transactions: [
      t("3577398", "08:01", 1.0, "digital-goods-17", 0.41),
      t("3577401", "08:02", 1.5, "digital-goods-17", 0.46),
      t("3577403", "08:03", 0.99, "digital-goods-22", 0.52),
      t("3577406", "08:05", 2.0, "digital-goods-22", 0.58),
      t("3577409", "08:07", 1.0, "digital-goods-31", 0.63),
      t("3577412", "08:11", 2480.0, "electronics-004", 0.94, { subject: true }),
    ],
    ...g(
      [
        ["card", "card", "card1 9500 · ••4417", { subject: true }],
        ["acct", "account", "C-10492"],
        ["dev", "device", "Windows · Chrome 91"],
        ["ip", "ip", "185.220.x.x (Tor exit)", { flagged: true }],
        ["m1", "merchant", "digital-goods-17"],
        ["m2", "merchant", "digital-goods-22"],
        ["m3", "merchant", "electronics-004"],
      ],
      [
        ["acct", "card", "OWNS"],
        ["card", "dev", "USED_ON"],
        ["dev", "ip", "CONNECTED_FROM"],
        ["card", "m1", "PAID ×2"],
        ["card", "m2", "PAID ×2"],
        ["card", "m3", "PAID $2,480"],
      ],
    ),
    signals: {
      velocity1h: 6,
      smallAuthsBeforeLarge: 5,
      amountZ: 7.8,
      newDevice: true,
      deviceAgeDays: 0,
      cardsOnDevice: 3,
      cardsOnIp: 14,
      emailDomainMismatch: false,
      addrChanged7d: false,
      hopsToConfirmedFraud: 2,
      communitySize: 18,
    },
    evidenceOutcomes: [
      { id: "denied", label: "Customer: “Not me”", description: "Customer confirms via app they did not make these transactions.", logOddsShift: 2.5, resolves: true },
      { id: "confirmed", label: "Customer: “That was me”", description: "Customer claims the purchases.", logOddsShift: -1.2, resolves: false },
      { id: "no_response", label: "No response (30 min)", description: "Customer did not respond within SLA.", logOddsShift: 0.3, resolves: false },
    ],
  },
  {
    id: "HHG-2042",
    title: "New device, $1,150 spend, customer possibly travelling",
    trigger: "risk_score",
    triggerDetail: "Model risk score 0.71 on TransactionID 3580077",
    openedAt: "2026-09-24T09:40:00Z",
    customer: { id: "C-22817", name: "Customer 22817", tenureMonths: 58, segment: "Premier" },
    subjectTxnId: "3580077",
    transactions: [
      t("3579120", "Sep 21", 64.2, "grocery-112", 0.04, { productCD: "C" }),
      t("3579655", "Sep 23", 212.0, "airline-009", 0.12),
      t("3580041", "09:31", 38.5, "rideshare-003", 0.33),
      t("3580077", "09:38", 1150.0, "luxury-retail-051", 0.71, { subject: true }),
    ],
    ...g(
      [
        ["card", "card", "card1 12695 · ••0921", { subject: true }],
        ["acct", "account", "C-22817"],
        ["dev_old", "device", "iOS 16 · Safari (14 mo)"],
        ["dev", "device", "Android 13 · new"],
        ["ip", "ip", "Lisbon mobile carrier"],
        ["email", "email", "gmail.com"],
        ["m", "merchant", "luxury-retail-051"],
        ["air", "merchant", "airline-009"],
      ],
      [
        ["acct", "card", "OWNS"],
        ["acct", "email", "HAS_EMAIL"],
        ["card", "dev_old", "USED_ON (412×)"],
        ["card", "dev", "USED_ON (2×)"],
        ["dev", "ip", "CONNECTED_FROM"],
        ["card", "air", "PAID $212"],
        ["card", "m", "PAID $1,150"],
      ],
    ),
    signals: {
      velocity1h: 2,
      smallAuthsBeforeLarge: 0,
      amountZ: 3.1,
      newDevice: true,
      deviceAgeDays: 0,
      cardsOnDevice: 1,
      cardsOnIp: 2,
      emailDomainMismatch: false,
      addrChanged7d: false,
      hopsToConfirmedFraud: null,
      communitySize: 3,
      customerTraveling: true,
      corporateNatIp: true,
    },
    evidenceOutcomes: [
      { id: "pass", label: "Step-up passed", description: "Customer completed biometric step-up on registered phone.", logOddsShift: -3.2, resolves: true },
      { id: "fail", label: "Step-up failed ×3", description: "Three failed OTP attempts from the new device.", logOddsShift: 2.8, resolves: true },
      { id: "no_response", label: "No response", description: "Step-up challenge expired unanswered.", logOddsShift: 0.6, resolves: false },
    ],
  },
  {
    id: "HHG-2043",
    title: "One device, nine cards — linked to confirmed mule case",
    trigger: "analyst_request",
    triggerDetail: "Analyst R. Mehta flagged device D-77A1 from case HHG-1877 follow-up",
    openedAt: "2026-09-24T10:05:00Z",
    customer: { id: "C-31555", name: "Customer 31555", tenureMonths: 2, segment: "Retail" },
    subjectTxnId: "3583310",
    transactions: [
      t("3583101", "Sep 22", 480.0, "p2p-transfer-02", 0.55, { productCD: "H" }),
      t("3583207", "Sep 23", 920.0, "p2p-transfer-02", 0.61, { productCD: "H" }),
      t("3583290", "07:55", 1890.0, "crypto-onramp-11", 0.77, { productCD: "S" }),
      t("3583310", "08:20", 3400.0, "crypto-onramp-11", 0.83, { productCD: "S", subject: true }),
    ],
    ...g(
      [
        ["card", "card", "card1 4141 · ••7730", { subject: true }],
        ["acct", "account", "C-31555"],
        ["dev", "device", "D-77A1 · Linux"],
        ["c2", "card", "••1180"],
        ["c3", "card", "••5521"],
        ["c4", "card", "••9043", { flagged: true }],
        ["c5", "card", "••3307"],
        ["c6", "card", "+4 more cards"],
        ["ip", "ip", "Corp NAT 62.x.x.x"],
        ["fraud_acct", "account", "HHG-1877 mule", { flagged: true }],
        ["m", "merchant", "crypto-onramp-11"],
      ],
      [
        ["acct", "card", "OWNS"],
        ["card", "dev", "USED_ON"],
        ["c2", "dev", "USED_ON"],
        ["c3", "dev", "USED_ON"],
        ["c4", "dev", "USED_ON"],
        ["c5", "dev", "USED_ON"],
        ["c6", "dev", "USED_ON"],
        ["dev", "ip", "CONNECTED_FROM"],
        ["c4", "fraud_acct", "OWNED_BY"],
        ["card", "m", "PAID $5,290"],
      ],
    ),
    signals: {
      velocity1h: 2,
      smallAuthsBeforeLarge: 0,
      amountZ: 4.4,
      newDevice: false,
      deviceAgeDays: 40,
      cardsOnDevice: 9,
      cardsOnIp: 23,
      emailDomainMismatch: true,
      addrChanged7d: false,
      hopsToConfirmedFraud: 2,
      communitySize: 27,
      corporateNatIp: true,
    },
    evidenceOutcomes: [
      { id: "ring_confirmed", label: "Analyst: ring confirmed", description: "Analyst confirms 6 of 9 cards moved funds to the same crypto wallet.", logOddsShift: 2.6, resolves: true },
      { id: "shared_kiosk", label: "Analyst: shared kiosk", description: "Device is a registered internet-café kiosk; cards unrelated.", logOddsShift: -2.4, resolves: true },
      { id: "inconclusive", label: "Inconclusive", description: "Analyst could not determine ownership of the wallet.", logOddsShift: 0.2, resolves: false },
    ],
  },
  {
    id: "HHG-2044",
    title: "Customer disputes $640 order from their own 2-year-old device",
    trigger: "customer_report",
    triggerDetail: "Customer called: “I never ordered this”",
    openedAt: "2026-09-24T11:30:00Z",
    customer: { id: "C-40931", name: "Customer 40931", tenureMonths: 44, segment: "Retail" },
    subjectTxnId: "3586002",
    transactions: [
      t("3585001", "Sep 12", 55.0, "fashion-020", 0.03),
      t("3585590", "Sep 18", 120.0, "fashion-020", 0.05),
      t("3586002", "Sep 23", 640.0, "fashion-020", 0.09, { subject: true }),
    ],
    ...g(
      [
        ["card", "card", "card1 7919 · ••2206", { subject: true }],
        ["acct", "account", "C-40931"],
        ["dev", "device", "macOS · Safari (26 mo)"],
        ["addr", "address", "addr1 299 (home)"],
        ["ip", "ip", "Home ISP"],
        ["m", "merchant", "fashion-020"],
        ["past", "account", "HHG-1602 dispute (cleared)", { flagged: false }],
      ],
      [
        ["acct", "card", "OWNS"],
        ["card", "dev", "USED_ON (388×)"],
        ["dev", "ip", "CONNECTED_FROM"],
        ["acct", "addr", "LIVES_AT"],
        ["m", "addr", "SHIPPED_TO"],
        ["card", "m", "PAID ×3"],
        ["acct", "past", "PRIOR_DISPUTE"],
      ],
    ),
    signals: {
      velocity1h: 1,
      smallAuthsBeforeLarge: 0,
      amountZ: 2.2,
      newDevice: false,
      deviceAgeDays: 790,
      cardsOnDevice: 1,
      cardsOnIp: 1,
      emailDomainMismatch: false,
      addrChanged7d: false,
      hopsToConfirmedFraud: null,
      communitySize: 2,
      customerReported: true,
    },
    evidenceOutcomes: [
      { id: "delivered", label: "Merchant: delivered, signed", description: "Merchant provides proof of delivery to home address with signature.", logOddsShift: -2.2, resolves: true },
      { id: "reshipped", label: "Merchant: reshipped", description: "Package was redirected to a different address after order.", logOddsShift: 2.4, resolves: true },
      { id: "no_response", label: "No merchant response", description: "Merchant did not respond within 5 days.", logOddsShift: 0.0, resolves: false },
    ],
  },
  {
    id: "HHG-2045",
    title: "Two-week-old identity, mismatched emails, fresh address",
    trigger: "risk_score",
    triggerDetail: "Model risk score 0.64 on TransactionID 3588120",
    openedAt: "2026-09-24T12:10:00Z",
    customer: { id: "C-51270", name: "Customer 51270", tenureMonths: 0, segment: "New" },
    subjectTxnId: "3588120",
    transactions: [
      t("3587410", "Sep 20", 25.0, "telecom-004", 0.22, { productCD: "C" }),
      t("3587991", "Sep 23", 310.0, "giftcards-008", 0.51),
      t("3588120", "13:02", 890.0, "giftcards-008", 0.64, { subject: true }),
    ],
    ...g(
      [
        ["card", "card", "card1 15066 · ••6612", { subject: true }],
        ["acct", "account", "C-51270"],
        ["e1", "email", "P: protonmail.com"],
        ["e2", "email", "R: yahoo.co.jp"],
        ["addr", "address", "addr1 441 (new, 5d)"],
        ["dev", "device", "Android 12 · 13d"],
        ["m", "merchant", "giftcards-008"],
        ["a2", "account", "C-51302 (same addr)"],
      ],
      [
        ["acct", "card", "OWNS"],
        ["acct", "e1", "PURCHASER_EMAIL"],
        ["card", "e2", "RECIPIENT_EMAIL"],
        ["acct", "addr", "LIVES_AT"],
        ["a2", "addr", "LIVES_AT"],
        ["card", "dev", "USED_ON"],
        ["card", "m", "PAID $1,200"],
      ],
    ),
    signals: {
      velocity1h: 1,
      smallAuthsBeforeLarge: 0,
      amountZ: 1.9,
      newDevice: false,
      deviceAgeDays: 13,
      cardsOnDevice: 1,
      cardsOnIp: 2,
      emailDomainMismatch: true,
      addrChanged7d: true,
      hopsToConfirmedFraud: 3,
      communitySize: 6,
    },
    evidenceOutcomes: [
      { id: "kyc_fail", label: "KYC doc check failed", description: "ID document does not match bureau record; SSN issued after DOB+18y anomaly.", logOddsShift: 2.7, resolves: true },
      { id: "kyc_pass", label: "KYC verified", description: "Document and liveness check passed; bureau file 6 years old.", logOddsShift: -2.6, resolves: true },
      { id: "no_response", label: "Customer abandoned", description: "Customer abandoned the verification flow.", logOddsShift: 1.0, resolves: false },
    ],
  },
  {
    id: "HHG-2046",
    title: "High model score on large but routine furniture purchase",
    trigger: "risk_score",
    triggerDetail: "Model risk score 0.82 on TransactionID 3590455",
    openedAt: "2026-09-24T13:45:00Z",
    customer: { id: "C-08812", name: "Customer 08812", tenureMonths: 96, segment: "Premier" },
    subjectTxnId: "3590455",
    transactions: [
      t("3589001", "Sep 02", 1420.0, "home-goods-007", 0.18),
      t("3589720", "Sep 15", 890.0, "home-goods-007", 0.12),
      t("3590455", "14:40", 3890.0, "furniture-019", 0.82, { subject: true }),
    ],
    ...g(
      [
        ["card", "card", "card1 2803 · ••5501", { subject: true }],
        ["acct", "account", "C-08812"],
        ["dev", "device", "Windows · Edge (5 y)"],
        ["ip", "ip", "Home ISP"],
        ["addr", "address", "addr1 204 (8 y)"],
        ["m", "merchant", "furniture-019"],
        ["m2", "merchant", "home-goods-007"],
      ],
      [
        ["acct", "card", "OWNS"],
        ["card", "dev", "USED_ON (1.9k×)"],
        ["dev", "ip", "CONNECTED_FROM"],
        ["acct", "addr", "LIVES_AT"],
        ["m", "addr", "SHIPS_TO"],
        ["card", "m2", "PAID ×2"],
        ["card", "m", "PAID $3,890"],
      ],
    ),
    signals: {
      velocity1h: 1,
      smallAuthsBeforeLarge: 0,
      amountZ: 1.4,
      newDevice: false,
      deviceAgeDays: 1850,
      cardsOnDevice: 1,
      cardsOnIp: 1,
      emailDomainMismatch: false,
      addrChanged7d: false,
      hopsToConfirmedFraud: null,
      communitySize: 1,
    },
    evidenceOutcomes: [
      { id: "confirmed", label: "Customer confirms", description: "Customer confirms purchase in app.", logOddsShift: -2.0, resolves: true },
      { id: "denied", label: "Customer denies", description: "Customer says they did not make the purchase.", logOddsShift: 3.5, resolves: true },
      { id: "no_response", label: "No response", description: "No reply to push notification.", logOddsShift: 0.0, resolves: false },
    ],
  },
];

/** Case memory: closed investigations (first four months). Grows as new cases resolve. */
export const CASE_MEMORY: PastCase[] = [
  { id: "HHG-1203", closedAt: "2026-06-02", pattern: "P1", outcome: "confirmed_fraud", summary: "7 micro-auths on digital goods then $1,900 electronics; Tor exit IP.", features: { smallAuthsBeforeLarge: 7, velocity1h: 8, newDevice: true, cardsOnIp: 11 }, analystDecision: "Blocked card, reissued, SAR filed with 3 linked cards." },
  { id: "HHG-1388", closedAt: "2026-06-19", pattern: "P1", outcome: "confirmed_fraud", summary: "Card testing via small donations, same IP cluster as HHG-1203.", features: { smallAuthsBeforeLarge: 4, velocity1h: 5, cardsOnIp: 14 }, analystDecision: "Blocked; IP cluster added to watchlist." },
  { id: "HHG-1450", closedAt: "2026-06-28", pattern: "P2", outcome: "cleared", summary: "New device abroad, large spend; customer was travelling, passed step-up.", features: { newDevice: true, customerTraveling: true, amountZ: 2.9 }, analystDecision: "Allowed after step-up; travel flag set." },
  { id: "HHG-1512", closedAt: "2026-07-04", pattern: "P2", outcome: "confirmed_fraud", summary: "New device + address change 2 days prior, $2.2k spend; step-up failed.", features: { newDevice: true, addrChanged7d: true, amountZ: 4.1 }, analystDecision: "Account frozen, credentials reset, customer refunded." },
  { id: "HHG-1602", closedAt: "2026-07-11", pattern: "P5", outcome: "cleared", summary: "Customer dispute on known device; merchant proved delivery. Customer withdrew.", features: { customerReported: true, deviceAgeDays: 700 }, analystDecision: "Dispute declined, customer educated." },
  { id: "HHG-1655", closedAt: "2026-07-15", pattern: "P5", outcome: "confirmed_fraud", summary: "Dispute on known device but shipment was redirected after order (household member).", features: { customerReported: true, deviceAgeDays: 500 }, analystDecision: "Refunded; merchant chargeback." },
  { id: "HHG-1740", closedAt: "2026-07-26", pattern: "P4", outcome: "confirmed_fraud", summary: "3-week identity, gift cards, emails across two domains, shared address with 2 other new accounts.", features: { emailDomainMismatch: true, addrChanged7d: true, deviceAgeDays: 20 }, analystDecision: "Account closed, SAR filed, bureau notified." },
  { id: "HHG-1811", closedAt: "2026-08-03", pattern: "P4", outcome: "cleared", summary: "New student account with mismatched emails; KYC passed.", features: { emailDomainMismatch: true, deviceAgeDays: 10 }, analystDecision: "Cleared; monitoring 30 days." },
  { id: "HHG-1877", closedAt: "2026-08-14", pattern: "P3", outcome: "confirmed_fraud", summary: "Mule ring: 11 cards through 2 devices, funds to crypto on-ramp.", features: { cardsOnDevice: 11, cardsOnIp: 25, hopsToConfirmedFraud: 1 }, analystDecision: "7 accounts frozen, SAR filed, law enforcement referral." },
  { id: "HHG-1902", closedAt: "2026-08-21", pattern: "P3", outcome: "cleared", summary: "Library kiosk device with many cards; no fund linkage.", features: { cardsOnDevice: 8, corporateNatIp: true }, analystDecision: "Cleared; device whitelisted as public kiosk." },
  { id: "HHG-1955", closedAt: "2026-08-27", pattern: "—", outcome: "cleared", summary: "Large home-goods purchase by long-tenure customer; model false positive.", features: { amountZ: 1.5, deviceAgeDays: 1500 }, analystDecision: "Allowed; model feedback logged." },
];
